Tracker:AddLocations("locations/Traverse Town.json")
Tracker:AddLocations("locations/Wonderland.json")
Tracker:AddLocations("locations/Agrabah.json")
Tracker:AddLocations("locations/Olympus Coliseum.json")
Tracker:AddLocations("locations/Castle Oblivion.json")
Tracker:AddLocations("locations/Monstro.json")
Tracker:AddLocations("locations/Halloween Town.json")
Tracker:AddLocations("locations/Atlantica.json")
Tracker:AddLocations("locations/Neverland.json")
Tracker:AddLocations("locations/Hollow Bastion.json")
Tracker:AddLocations("locations/100 Acre Wood.json")
Tracker:AddLocations("locations/Twilight Town.json")
Tracker:AddLocations("locations/Destiny Islands.json")
Tracker:AddLocations("locations/Floors.json")
Tracker:AddLocations("locations/Level Sleights.json")
Tracker:AddLocations("locations/Heartless.json")
Tracker:AddLocations("locations/Overview.json")
